name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:

    - name: Assign issues with `bug` label to their project
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/orgs/way-of-elendil/projects/4'
